services:
  uams-db:
    image: mysql:8.0
    container_name: uams-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: UAMS
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - uams-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  uams-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uams-app
    restart: unless-stopped
    ports:
      - "8081:8080" # remove when using reverse proxy
    read_only: true
    tmpfs:
      - /tmp
    env_file:
      - .env
    environment:
      - JAVA_OPTS="-Xms256m -Xmx512m"
      - DB_URL=jdbc:mysql://uams-db:3306/UAMS?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      uams-db:
        condition: service_healthy
    mem_limit: 512m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  uams-db-data:
