spring.jpa.show-sql=false
logging.level.com.example.uams=INFO

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

springdoc.show-actuator=false
springdoc.swagger-ui.disable-swagger-default-url=true