spring.jpa.show-sql=true
logging.level.com.example.uams=DEBUG

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

springdoc.show-actuator=false
springdoc.swagger-ui.disable-swagger-default-url=true